import type { NextPage } from 'next';
import Head from 'next/head';
import { Hero, About, Management, BrandingDesign, Projects } from '@components/home';
import styles from './index.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WeEngage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <About />
        <Management />
        <BrandingDesign />
        <Projects />
      </main>
    </div>
  );
};

export default Home;
